### ISSUE TITLE
Popup doesnt open in Safari on MacOS

### ISSUE THREAD

**Issue by kgoedecke** [kgoedecke/react-oauth-popup#23]
I'm using `react-oauth-popup` with NextJS and the popup works fine in Firefox and Chrome but it only shortly appears in Safari and then closes immediately. 

Has anyone of you experienced this issue before?

**Comment by akiladevinda** [comment]
Hi @kgoedecke  Any solution for this? I had the same issue

**Comment by kgoedecke** [comment]
@akiladevinda I actually  re-wrote the whole thing and will probably open source it one of these days.

**Comment by akiladevinda** [comment]
@kgoedecke  Did you able to make your one open source? Any link?

**Comment by sismanis** [comment]
@kgoedecke can you open source your fork or at least post a snippet of the fix? Thanks!

**Comment by kgoedecke** [comment]
@akiladevinda @sismanis I havent gotten around to it yet. I hope I can do it this week.

**Comment by Ramshackle-Jamathon** [comment]
@kgoedecke I'm happy to transfer ownership of this repo to you if you'd like. I don't have the time to maintain this. 

I'm also not sure there's a way to get popups working on safari, afaik you need to set `noopener` for the popup for it to stay open but that also prevents the the parent window from accessing any information inside the popup.

**Comment by kgoedecke** [comment]
It works in my solution. But i took a different approach, fully functional no class components.

**Comment by kgoedecke** [comment]
@Ramshackle-Jamathon do you think it makes sense to completely delete all code and replace it with my version? :/

**Comment by Ramshackle-Jamathon** [comment]
@kgoedecke sure! I think you'd just wanna do a major version bump

**Comment by blieb** [comment]
Sounds interesting, hope we can expect the update soon. Looking into the same now.

**Comment by kgoedecke** [comment]
@akiladevinda @sismanis this should be fixed now, just released v1.0.0
